### PR TITLE
Update Tern sample configuration in README.

### PR DESCRIPTION
**Pull request by oblitum**
As of https://github.com/marijnh/tern/issues/281, it seems using this kind of glob
pattern should be a better approach.

### CODE REVIEW

**Comment by Slava** [comment]
It didn't work as of the time of writing that README.

**Comment by oblitum** [comment]
> It didn't work as of the time of writing that README.

I imagined this but, will this be a problem at accepting the pull?

Thanks for your work, it's being nice to start program Meteor and turn my Vim setup so friendly to it.

**Comment by Slava** [comment]
I consider it to be a problem, because people will look at that non-working example and try to use it without success.

**Comment by oblitum** [comment]
You mean for people that for some reason is not in an up to date setup?

**Comment by Slava** [comment]
I don't think the bug is fixed. Looking at the changelog, tern still uses the same version of glob, which is buggy.

**Comment by oblitum** [comment]
ah, ok then but, I started using it and I thought from the discussion that it stopped being a problem, I'm a bit confused now. Do you recommend sticking with the old approach for any reason, as far as I can see, the shorter glob pattern isn't being a problem for me yet, but it's difficult to diagnostic whether it's working just like the former approach, for half-working compared to it.

**Comment by Slava** [comment]
I tried to debug it like a year ago w/o any success. Sometimes the glob would work, other time it would just not return anything. Now to think about it, I think it could be related to the node's EMFILE errors or incorrect error-handling. I don't know.

**Comment by oblitum** [comment]
OK, thanks for the help anyway.

**Pull request closed without merging**
